name: TestPullRequest

on:
  pull_request:
    branches: master

  workflow_dispatch:

jobs:                 
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: :butterfly-qr-android:test
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test_results
          path: butterfly-qr-android/build/reports/tests/testDebugUnitTest/
          retention-days: 10
